### ISSUE TITLE
Slight jank on initial experiment page load

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/experiments-viewer#103]
When hitting an experiment on EV for the first time after a refresh the rendering can be a little wonky.. some graphs don't come through, or they might not update, and hover text might only show 'control' and not the other cohorts. The problems seem to resolve if you toggle one of the cohorts once, or if you switch to a different experiment and then switch back, but you can get them to happen again if you hit refresh.

**Comment by openjck** [comment]
It looks like the charts that don't load are missing data for some populations in the back-end. For example, populations A and B are enabled, but there's only data for B. The back-end isn't the problem, the front-end should handle that case.

Continuing to dig into it...

**Comment by openjck** [comment]
5b63124 fixed the chart loading issue. I also can't reproduce the hover text issue. Some charts don't have hover text for certain populations, but only because the dataset has no data for those populations. Those same charts are also missing lines for those populations as expected.

There is an issue where the disabling one population sometimes causes the line for another population to disappear. I'll open a separate issue for that.

**Comment by openjck** [comment]
> I'll open a separate issue for that.

See #120
