### ISSUE TITLE
I hate the apply button and it should be burned by fire

### ISSUE THREAD

**Issue by gregglind** [mozilla/experiments-viewer#114]
Warning:  bold / untested claims below!

I **think** this is a better solution for 'change experiment':

- Changing the dropdown should change the series.  It's too easy to change the drop down and forget / miss the apply button.  
- I actually don't know if this is true
- I am nervous to ask you to mess with forms/action responders, because breakage.

**Comment by gregglind** [comment]
(another alternative)

- ONLY display the button when the selector is changed.  You already have code to change the styling and 'disable' at:  https://github.com/mozilla/experiments-viewer/blob/cd6e4c900ed4f21151b06d732b2b542a3f9aa0b1/viewer/static/js/app/components/views/dataset-control.js#L18
- adding an extra class `hidden` when `props.isDisabled` is on.  `classnames` or `classSet` or such?  Seems like a very small thing to test :)

https://eric.blog/2015/01/19/dynamically-add-classes-react-classset/

**Comment by openjck** [comment]
I'm actually fine with removing the *apply* button and making the dropdown have an immediate effect. All of the other controls on the page take effect immediately, so it would be more [consistent](http://goodui.org/#27).

**Comment by gregglind** [comment]
I might suggest trying it in stages, or not super ripping it all out yet :)  Seems like the sort of thing that people might want to revert at an inconvenient time.  Ultimately, it is your call :)

**Comment by rafrombrc** [comment]
I'm +1 to having the button appear and disappear, rather than simply enabling and disabling itself as appropriate. I'm +0 to removing the apply button altogether... not strongly against it, but question whether it's the right choice. The reasons for not having an apply button are fairly obvious: apply buttons in general can be annoying, and it's inconsistent with the other controls. There are reasons why we have it, though:

* The cohorts selection updates nearly instantaneously, so selecting and unselecting options there don't slow users down at all. Changing the experiment involves an API roundtrip and a much more comprehensive screen update, potentially a lot more latency.
* When changing from one experiment to the next, you might lose the state re: the combination of OS / cohorts that you're looking at.

With both issues above, the apply button means folks are much less likely to accidentally annoy themselves with either latency and/or losing their state by simply changing the dropdown value. I don't know how much these will really be problems, but I at least want to surface that those are the reasons for the button in the first place.

**Comment by rafrombrc** [comment]
Okay, I've changed my mind here... the page refresh when you switch experiments on the production site is not painfully slow, let's just get rid of the 'apply' button altogether, we can revisit if changing instantly when the drop down is switched ends up being a problem.

**Comment by openjck** [comment]
:fire: :fire: :fire: `apply` :fire: :fire: :fire:

👩‍🚒 😮 🤣 💨
