### ISSUE TITLE
API does not return any populations when ?sg query parameter is not specified

### ISSUE THREAD

**Issue by openjck** [mozilla/experiments-viewer#138]
The following URL does not return any data:
https://moz-experiments-viewer-staging.herokuapp.com/metric/303/?ds=10&pop=control,versionA,versionB

But the following does:
https://moz-experiments-viewer-staging.herokuapp.com/metric/303/?ds=10&pop=control,versionA,versionB&sg=All

The first should return identical data as the second.

**Comment by robhudson** [comment]
Good catch. Here's what happened...

The latest upstream parquet file changed the value from a null to the string "All" and in my import script I followed that pattern as well. So in the database to select the dataset for the "All" subgroup you actually have to filter by "All". But I failed to update the code to match the import and it was still filtering by the empty string to mean "All".

In the first URL, the lack of a `sg` query string parameter defaulted to filter by `subgroup=''` and since for that dataset there was no data matching that criteria it returned no data. Explicitly passing `?sg=All` fixed it.

I'll update the code and tests to follow the import script change. Apologies I missed this.

Note: I will also update the fixtures to follow this change as well otherwise the fixtures and the import data will not coincide.
