### ISSUE TITLE
Show experiments in order in the dropdown

### ISSUE THREAD

**Issue by openjck** [mozilla/experiments-viewer#36]
For example, the experiment with ID 1 would be shown first, 2 second, and so on. It might be easiest to do this on the back-end and have the API guarantee this order.

**Comment by gregglind** [comment]
I am not sure what the right ordering should be.  Alpha is better than nothing.  By last updated is better, but hard to see how to do.

**Comment by robhudson** [comment]
The /datasets/ API is being ordered by date descending, but since the date is updated during each import, it's a bit useless.

If we ordered by ID that might make more sense and be close to a "experiment creating order" since new experiments that get added to the table get a higher ID.

A longer term solution would probably be to fetch this data from normandy. I see that there is a `recipe['approval_request']['created']` date/time stamp we can likely use.
